### ISSUE TITLE
angry-3

### ISSUE THREAD

**Issue by mgomez08** [uzair-ashraf/anime-reaction-api#6]
![angry-3](https://user-images.githubusercontent.com/49167174/94980845-0907c400-04f3-11eb-909a-fca580edf83c.gif)

**Comment by mgomez08** [comment]
@uzair-ashraf, I don't know  how to add the new reaction label, I think you can only add it, if so, I'll wait for you to add the label to open a PR.

**Comment by uzair-ashraf** [comment]
@mgomez08 Feel free to create a pull request so I can merge!

**Comment by mgomez08** [comment]
> @mgomez08 Feel free to create a pull request so I can merge!

I just made the Pull Request  #7 , hopefully it's okay with the format you asked for. For some reason hacktoberfest reports me as Ineligible Repository, you can add the "hacktoberfest" topic to their repository, thank you very much!

**Comment by uzair-ashraf** [comment]
Approved and I added the topic, thanks @mgomez08 !!
